name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  checks: write
  contents: write
  pull-requests: write
  actions: write
jobs:
  lint:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Node.js dependencies
        run: yarn install
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
