name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all|write-all
jobs:
  lint:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      actions: read|write|none
      checks: read|write|none
      contents: read|write|none
      deployments: read|write|none
      id-token: read|write|none
      issues: read|write|none
      discussions: read|write|none
      packages: read|write|none
      pages: read|write|none
      pull-requests: read|write|none
      repository-projects: read|write|none
      security-events: read|write|none
      statuses: read|write|none
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Node.js dependencies
        run: yarn install
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
